spring.application.name=ledgerly

# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ledgerly?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# LOGGING
# ===============================
logging.config=classpath:log4j2.xml
# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ledgerly-group
spring.kafka.consumer.auto-offset-reset=earliest

server.port=8080
